package io.github.kraowx.shibbyapp.net;

public enum ResponseType
{
    VERSION, VERIFY_PATREON_ACCOUNT,
    ALL, FILES, TAGS, SERIES, PATREON_FILES,
    INVALID_REQUEST, FEATURE_NOT_SUPPORTED, TOO_MANY_REQUESTS, BAD_ACCOUNT
}
